### ISSUE TITLE
ViewControllers not loaded if addViewController not at init

### ISSUE THREAD

**Issue by sleith** [aokizen/SPSlideTabBarController#1]
Hi sir,
firstly thank you for your great lib :)

I dynamically load the tabs based on server data.
So i call http first to get my tab list.
Then i construct using  [self addViewController:];
It works, i can see the tab bar and the titles.
But the view controllers is not showing (viewDidLoad is not called).
only after i drag to slide (even small drag) then the viewDidLoad triggered and then i can see the content.

Any idea how to solve this?
Thank you

**Comment by aokizen** [comment]
Hi sletith,

I have reproduced the bug you mentioned above. there are two problems I found. 
I have pushed a new **branch** [**hotfix**] trying to fix it.

You can try the new code. 
if the update can solve your problem, I will release a new version.
if it can't, I think you'd better show me some code then I can locate the problem more clearly .

Thank you.

**Comment by sleith** [comment]
thanks sir. it works ^^
